"""PDF report generation — doctor-ready and parent-friendly versions.

Both reports are built from the same `findings` dict produced by
`src.runner.run_all_analyses`. The doctor version is dense and quantitative;
the parent version emphasizes plain language and the questions worth asking.

Uses reportlab (pure Python, no external binaries). Output is a single
in-memory bytes object that Streamlit can stream as a download.
"""

from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
)


# ─── Styles ──────────────────────────────────────────────────────────────────

def _styles():
    base = getSampleStyleSheet()
    s = {
        "title":   ParagraphStyle("title", parent=base["Title"],
                                  fontSize=18, spaceAfter=6),
        "subtitle": ParagraphStyle("subtitle", parent=base["Normal"],
                                   fontSize=10, textColor=colors.grey,
                                   spaceAfter=12),
        "h2":      ParagraphStyle("h2", parent=base["Heading2"],
                                  fontSize=13, spaceBefore=14, spaceAfter=6,
                                  textColor=colors.HexColor("#2E4A6B")),
        "body":    ParagraphStyle("body", parent=base["Normal"],
                                  fontSize=10, leading=14, spaceAfter=6),
        "small":   ParagraphStyle("small", parent=base["Normal"],
                                  fontSize=8, textColor=colors.grey),
        "warning": ParagraphStyle("warning", parent=base["Normal"],
                                  fontSize=10, leading=14,
                                  textColor=colors.HexColor("#A05500"),
                                  spaceAfter=6),
    }
    return s


# ─── Helpers ────────────────────────────────────────────────────────────────

def _kv_table(rows: list[tuple[str, str]], col_widths=(7 * cm, 9 * cm)) -> Table:
    """Two-column key/value table."""
    t = Table(rows, colWidths=col_widths)
    t.setStyle(TableStyle([
        ("FONT", (0, 0), (-1, -1), "Helvetica", 10),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("LINEBELOW", (0, 0), (-1, -1), 0.3, colors.lightgrey),
        ("FONT", (0, 0), (0, -1), "Helvetica-Bold", 10),
    ]))
    return t


def _interp_color(interpretation: str) -> str:
    return {
        "below": "#A05500",
        "severely_slow": "#B00020",
        "mildly_slow": "#A05500",
        "above": "#0E5C2F",
        "in": "#0E5C2F",
        "age_appropriate": "#0E5C2F",
        "predominantly_complex": "#A05500",
        "predominantly_simple": "#0E5C2F",
    }.get(interpretation, "#444444")


def _header(story: list, st: dict, title: str, subtitle: str):
    story.append(Paragraph(title, st["title"]))
    story.append(Paragraph(subtitle, st["subtitle"]))


def _disclaimer(story: list, st: dict, audience: str):
    text = {
        "doctor": (
            "<b>Disclaimer.</b> Generated by KCNQ3-Lens, an open-source research-grade "
            "quantitative EEG tool. Not a medical device, not clinically validated. "
            "All findings should be interpreted in the full clinical context."
        ),
        "parent": (
            "<b>Important.</b> This report comes from an open-source analysis tool, "
            "not a doctor. The numbers in here are conversation starters — please "
            "discuss every finding with your child's neurologist before drawing "
            "any conclusions. The tool does not diagnose, treat, or prescribe."
        ),
    }[audience]
    story.append(Spacer(1, 0.5 * cm))
    story.append(Paragraph(text, st["small"]))


# ─── Doctor PDF ──────────────────────────────────────────────────────────────

def build_doctor_pdf(
    findings: dict[str, Any],
    age_years: float | None = None,
    variant: str | None = None,
    patient_label: str | None = None,
    recording_label: str | None = None,
) -> bytes:
    """Generate a dense, technical PDF for clinicians."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm,
        topMargin=2 * cm, bottomMargin=2 * cm,
    )
    st = _styles()
    story = []

    # Header
    title = "KCNQ3-Lens Quantitative EEG Report"
    sub_parts = [datetime.now().strftime("%Y-%m-%d %H:%M")]
    if patient_label:
        sub_parts.append(f"Patient: {patient_label}")
    if age_years is not None:
        sub_parts.append(f"Age: {age_years:.1f} y")
    if variant:
        sub_parts.append(f"Variant: {variant}")
    if recording_label:
        sub_parts.append(f"Recording: {recording_label}")
    _header(story, st, title, " · ".join(sub_parts))

    # Section 1: Topography
    topo = findings.get("topography")
    if topo:
        story.append(Paragraph("Spike Topography (per-channel kurtosis)", st["h2"]))
        story.append(Paragraph(
            f"Analyzed {topo.get('epochs_analyzed', '?')} epochs. "
            "Higher median kurtosis = more sharp-transient activity. "
            "Normal background ≈ 3–5; &gt;10 indicates epileptiform.",
            st["body"],
        ))
        rows = [["Channel", "Median", "P90", "% epochs >10"]]
        for ch in topo.get("all_channels", []):
            rows.append([
                ch.get("name", ""),
                f"{ch.get('median', 0):.2f}",
                f"{ch.get('p90', 0):.2f}",
                f"{ch.get('pct_high_kurtosis', 0):.1f}%",
            ])
        tbl = Table(rows, colWidths=(3 * cm, 3 * cm, 3 * cm, 3 * cm))
        tbl.setStyle(TableStyle([
            ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 9),
            ("FONT", (0, 1), (-1, -1), "Helvetica", 9),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E8EEF5")),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
            ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
        ]))
        story.append(tbl)

    # Section 2: Spindles
    sp = findings.get("spindles")
    if sp:
        story.append(Paragraph("Sleep Spindles", st["h2"]))
        rows = [
            ("Channel", sp.get("channel", "?")),
            ("Method", sp.get("method", "?")),
            ("Spindles detected", str(sp.get("n_spindles", 0))),
            ("Duration analyzed (h)", f"{sp.get('duration_hours', 0):.2f}"),
            ("Density (/min)", f"{sp.get('density_per_minute', 0):.2f}"),
            ("Mean duration (s)", f"{sp.get('mean_duration_s', 0):.2f}"),
            ("Median peak frequency (Hz)", f"{sp.get('median_peak_freq_hz', 0):.1f}"),
        ]
        norm = sp.get("age_normative_range")
        if norm:
            rows.append(("Age-normative range (/min)", f"{norm[0]}–{norm[1]}"))
        rows.append(("Interpretation", sp.get("interpretation", "")))
        story.append(_kv_table(rows))

    # Section 3: Background
    bg = findings.get("background")
    if bg:
        story.append(Paragraph("Background Power", st["h2"]))
        rows = [
            ("Posterior dominant rhythm (Hz)",
             f"{bg.get('posterior_dominant_rhythm_hz', 0):.1f}"),
            ("Delta / Alpha ratio", f"{bg.get('delta_alpha_ratio', 0):.2f}"),
            ("Delta % / Theta %",
             f"{bg.get('delta_pct', 0):.0f}% / {bg.get('theta_pct', 0):.0f}%"),
            ("Alpha % / Beta %",
             f"{bg.get('alpha_pct', 0):.0f}% / {bg.get('beta_pct', 0):.0f}%"),
            ("Channels used", ", ".join(bg.get("channels_used", []))),
        ]
        norm = bg.get("age_normative_pdr")
        if norm:
            rows.append(("Age-normative PDR (Hz)", f"{norm[0]}–{norm[1]}"))
        rows.append(("Interpretation", bg.get("interpretation", "")))
        story.append(_kv_table(rows))

    # Section 4: Bursts
    br = findings.get("bursts")
    if br:
        story.append(Paragraph("Sustained Rhythmic Bursts", st["h2"]))
        rows = [
            ("Primary channel", br.get("primary_channel", "?")),
            ("Search window (h)", f"{br.get('search_window_hours', 0):.2f}"),
            ("Bursts ≥3s", str(br.get("n_bursts", 0))),
            ("Bursts ≥5s", str(br.get("n_bursts_5s_or_longer", 0))),
            ("Bursts ≥10s", str(br.get("n_bursts_10s_or_longer", 0))),
            ("Maximum duration (s)", f"{br.get('max_duration_s', 0):.1f}"),
            ("Median duration (s)", f"{br.get('median_duration_s', 0):.1f}"),
        ]
        story.append(_kv_table(rows))

    # Section 5: Morphology
    m = findings.get("morphology")
    if m:
        story.append(Paragraph("Spike Morphology", st["h2"]))
        rows = [
            ("Channel", m.get("channel", "?")),
            ("Events detected", f"{m.get('n_events', 0)} ({m.get('events_per_minute', 0):.1f}/min)"),
            ("% simple spikes (<70ms)", f"{m.get('pct_simple_spikes', 0):.0f}%"),
            ("% sharp waves (70–200ms)", f"{m.get('pct_sharp_waves', 0):.0f}%"),
            ("% complex spike-wave (≥200ms)", f"{m.get('pct_complex_spike_wave', 0):.0f}%"),
            ("Polyspike fraction", f"{m.get('polyspike_fraction', 0):.0f}%"),
            ("Duration p25/p50/p75 (ms)",
             f"{m.get('duration_p25_ms', 0)}/"
             f"{m.get('duration_p50_ms', 0)}/"
             f"{m.get('duration_p75_ms', 0)}"),
            ("Classification", m.get("classification", "")),
        ]
        story.append(_kv_table(rows))

    _disclaimer(story, st, "doctor")
    doc.build(story)
    return buf.getvalue()


# ─── Parent PDF ──────────────────────────────────────────────────────────────

def build_parent_pdf(
    findings: dict[str, Any],
    age_years: float | None = None,
    variant: str | None = None,
    interpretation: str | None = None,
    patient_label: str | None = None,
) -> bytes:
    """Generate a plain-language PDF for families to share / keep."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm,
        topMargin=2 * cm, bottomMargin=2 * cm,
    )
    st = _styles()
    story = []

    # Header
    title = "EEG Findings — Parent Summary"
    sub_parts = [datetime.now().strftime("%Y-%m-%d %H:%M")]
    if patient_label:
        sub_parts.append(patient_label)
    if age_years is not None:
        sub_parts.append(f"Age {age_years:.0f}")
    if variant:
        sub_parts.append(variant)
    _header(story, st, title, " · ".join(sub_parts))

    # Quick summary of the five analyses in plain language
    story.append(Paragraph("What was measured", st["h2"]))

    summary_rows = []

    sp = findings.get("spindles")
    if sp:
        norm = sp.get("age_normative_range") or (None, None)
        norm_str = f"({norm[0]}–{norm[1]} typical)" if norm[0] else ""
        flag = "⚠ low" if sp.get("interpretation") == "below" else ""
        summary_rows.append([
            "Sleep spindles",
            f"{sp.get('density_per_minute', 0):.2f} per minute {norm_str} {flag}",
        ])

    bg = findings.get("background")
    if bg:
        norm = bg.get("age_normative_pdr") or (None, None)
        norm_str = f"({norm[0]}–{norm[1]} Hz typical)" if norm[0] else ""
        flag = ""
        if bg.get("interpretation") == "severely_slow":
            flag = "⚠ slow"
        elif bg.get("interpretation") == "mildly_slow":
            flag = "mildly slow"
        summary_rows.append([
            "Background rhythm",
            f"{bg.get('posterior_dominant_rhythm_hz', 0):.1f} Hz {norm_str} {flag}",
        ])

    br = findings.get("bursts")
    if br:
        flag = "⚠ notable" if br.get("n_bursts_10s_or_longer", 0) > 0 else ""
        summary_rows.append([
            "Long rhythmic bursts",
            f"{br.get('n_bursts_10s_or_longer', 0)} bursts ≥10 seconds {flag}",
        ])

    m = findings.get("morphology")
    if m:
        flag = "⚠ complex" if m.get("classification") == "predominantly_complex" else ""
        summary_rows.append([
            "Spike type",
            f"{m.get('pct_complex_spike_wave', 0):.0f}% complex spike-wave {flag}",
        ])

    topo = findings.get("topography")
    if topo and topo.get("top_channels"):
        tops = topo["top_channels"][:3]
        tops_str = ", ".join(f"{t['name']} ({t['median_kurtosis']:.1f})" for t in tops)
        summary_rows.append([
            "Strongest activity location",
            tops_str,
        ])

    if summary_rows:
        story.append(_kv_table(summary_rows))

    # AI interpretation if available
    if interpretation:
        story.append(Spacer(1, 0.4 * cm))
        story.append(Paragraph("Plain-language interpretation", st["h2"]))
        # The interpretation is markdown; reportlab can handle basic HTML-like tags
        # Convert markdown headers and bullets to a basic readable form
        lines = interpretation.split("\n")
        for line in lines:
            line = line.strip()
            if not line:
                story.append(Spacer(1, 0.15 * cm))
                continue
            if line.startswith("###"):
                story.append(Paragraph(line.lstrip("# ").strip(), st["h2"]))
            elif line.startswith("##"):
                story.append(Paragraph(line.lstrip("# ").strip(), st["h2"]))
            elif line.startswith("- ") or line.startswith("* "):
                story.append(Paragraph("• " + line[2:], st["body"]))
            else:
                story.append(Paragraph(line, st["body"]))

    # Closing reminder
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph(
        "Bring this report to your next appointment with your child's neurologist. "
        "The numbers above are starting points for conversation, not diagnoses.",
        st["warning"],
    ))

    _disclaimer(story, st, "parent")
    doc.build(story)
    return buf.getvalue()
