"""PDF report generation — doctor-ready and parent-friendly versions.

Both reports are built from the same `findings` dict produced by
`src.runner.run_all_analyses`. The doctor version is dense and quantitative;
the parent version emphasizes plain language and the questions worth asking.

v0.5 additions:
- SWI per sleep stage (with CSWS threshold check)
- Wake / NREM / REM spike-rate split with activation factor
- Bilateral synchrony / spread pattern
- Methods section with software version, analysis timestamp,
  algorithm parameters
- Optional sample EEG traces (passed in by caller as PNG bytes)

Uses reportlab (pure Python, no external binaries). Output is a single
in-memory bytes object that Streamlit can stream as a download.
"""

from __future__ import annotations

import io
from datetime import datetime
from typing import Any

try:
    from src import __version__ as _VERSION
except Exception:
    _VERSION = "0.5.0"

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak,
)


# ─── Styles ──────────────────────────────────────────────────────────────────

def _styles():
    base = getSampleStyleSheet()
    s = {
        "title":   ParagraphStyle("title", parent=base["Title"],
                                  fontSize=18, spaceAfter=6),
        "subtitle": ParagraphStyle("subtitle", parent=base["Normal"],
                                   fontSize=10, textColor=colors.grey,
                                   spaceAfter=12),
        "h2":      ParagraphStyle("h2", parent=base["Heading2"],
                                  fontSize=13, spaceBefore=14, spaceAfter=6,
                                  textColor=colors.HexColor("#2E4A6B")),
        "body":    ParagraphStyle("body", parent=base["Normal"],
                                  fontSize=10, leading=14, spaceAfter=6),
        "small":   ParagraphStyle("small", parent=base["Normal"],
                                  fontSize=8, textColor=colors.grey),
        "warning": ParagraphStyle("warning", parent=base["Normal"],
                                  fontSize=10, leading=14,
                                  textColor=colors.HexColor("#A05500"),
                                  spaceAfter=6),
    }
    return s


# ─── Helpers ────────────────────────────────────────────────────────────────

def _kv_table(rows: list[tuple[str, str]], col_widths=(7 * cm, 9 * cm)) -> Table:
    """Two-column key/value table."""
    t = Table(rows, colWidths=col_widths)
    t.setStyle(TableStyle([
        ("FONT", (0, 0), (-1, -1), "Helvetica", 10),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("LINEBELOW", (0, 0), (-1, -1), 0.3, colors.lightgrey),
        ("FONT", (0, 0), (0, -1), "Helvetica-Bold", 10),
    ]))
    return t


def _interp_color(interpretation: str) -> str:
    return {
        "below": "#A05500",
        "severely_slow": "#B00020",
        "mildly_slow": "#A05500",
        "above": "#0E5C2F",
        "in": "#0E5C2F",
        "age_appropriate": "#0E5C2F",
        "predominantly_complex": "#A05500",
        "predominantly_simple": "#0E5C2F",
    }.get(interpretation, "#444444")


def _header(story: list, st: dict, title: str, subtitle: str):
    story.append(Paragraph(title, st["title"]))
    story.append(Paragraph(subtitle, st["subtitle"]))


def _disclaimer(story: list, st: dict, audience: str):
    text = {
        "doctor": (
            "<b>Disclaimer.</b> Generated by KCNQ3-Lens, an open-source research-grade "
            "quantitative EEG tool. Not a medical device, not clinically validated. "
            "All findings should be interpreted in the full clinical context."
        ),
        "parent": (
            "<b>Important.</b> This report comes from an open-source analysis tool, "
            "not a doctor. The numbers in here are conversation starters — please "
            "discuss every finding with your child's neurologist before drawing "
            "any conclusions. The tool does not diagnose, treat, or prescribe."
        ),
    }[audience]
    story.append(Spacer(1, 0.5 * cm))
    story.append(Paragraph(text, st["small"]))


# ─── Doctor PDF ──────────────────────────────────────────────────────────────

def build_doctor_pdf(
    findings: dict[str, Any],
    age_years: float | None = None,
    variant: str | None = None,
    patient_label: str | None = None,
    recording_label: str | None = None,
    sample_traces: list[tuple[str, bytes]] | None = None,
) -> bytes:
    """Generate a dense, technical PDF for clinicians.

    sample_traces : list of (caption, png_bytes)
        Optional EEG sample-trace images embedded in the PDF.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm,
        topMargin=2 * cm, bottomMargin=2 * cm,
    )
    st = _styles()
    story = []

    # Header
    title = "KCNQ3-Lens Quantitative EEG Report"
    sub_parts = [datetime.now().strftime("%Y-%m-%d %H:%M")]
    if patient_label:
        sub_parts.append(f"Patient: {patient_label}")
    if age_years is not None:
        sub_parts.append(f"Age: {age_years:.1f} y")
    if variant:
        sub_parts.append(f"Variant: {variant}")
    if recording_label:
        sub_parts.append(f"Recording: {recording_label}")
    _header(story, st, title, " · ".join(sub_parts))

    # ── v0.6: Clinical Impression (TOP OF REPORT) ────────────────────────
    impression = findings.get("clinical_impression")
    if impression:
        story.append(Paragraph("Impression", st["h2"]))
        story.append(Paragraph(impression, st["body"]))

    # ── v0.6: Recommendations ───────────────────────────────────────────
    recs = findings.get("clinical_recommendations") or []
    if recs:
        story.append(Paragraph("Recommendations / questions to discuss", st["h2"]))
        for r in recs:
            story.append(Paragraph(f"• {r}", st["body"]))

    # ── v0.7: Negative findings ─────────────────────────────────────────
    neg = findings.get("negative_findings") or []
    if neg:
        story.append(Paragraph("Negative findings (checked, not present)", st["h2"]))
        for n in neg:
            story.append(Paragraph(f"• {n}", st["body"]))

    # Section 1: Topography
    topo = findings.get("topography")
    if topo:
        story.append(Paragraph("Spike Topography (per-channel kurtosis)", st["h2"]))
        story.append(Paragraph(
            f"Analyzed {topo.get('epochs_analyzed', '?')} epochs. "
            "Higher median kurtosis = more sharp-transient activity. "
            "Normal background ≈ 3–5; &gt;10 indicates epileptiform.",
            st["body"],
        ))
        rows = [["Channel", "Median", "P90", "% epochs >10"]]
        for ch in topo.get("all_channels", []):
            rows.append([
                ch.get("name", ""),
                f"{ch.get('median', 0):.2f}",
                f"{ch.get('p90', 0):.2f}",
                f"{ch.get('pct_high_kurtosis', 0):.1f}%",
            ])
        tbl = Table(rows, colWidths=(3 * cm, 3 * cm, 3 * cm, 3 * cm))
        tbl.setStyle(TableStyle([
            ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 9),
            ("FONT", (0, 1), (-1, -1), "Helvetica", 9),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E8EEF5")),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
            ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
        ]))
        story.append(tbl)

    # Section 2: Spindles
    sp = findings.get("spindles")
    if sp:
        story.append(Paragraph("Sleep Spindles", st["h2"]))
        rows = [
            ("Channel", sp.get("channel", "?")),
            ("Method", sp.get("method", "?")),
            ("Spindles detected", str(sp.get("n_spindles", 0))),
            ("Duration analyzed (h)", f"{sp.get('duration_hours', 0):.2f}"),
            ("Density (/min)", f"{sp.get('density_per_minute', 0):.2f}"),
            ("Mean duration (s)", f"{sp.get('mean_duration_s', 0):.2f}"),
            ("Median peak frequency (Hz)", f"{sp.get('median_peak_freq_hz', 0):.1f}"),
        ]
        norm = sp.get("age_normative_range")
        if norm:
            rows.append(("Age-normative range (/min)", f"{norm[0]}–{norm[1]}"))
        rows.append(("Interpretation", sp.get("interpretation", "")))
        story.append(_kv_table(rows))

    # Section 3: Background
    bg = findings.get("background")
    if bg:
        story.append(Paragraph("Background Power", st["h2"]))
        rows = [
            ("Posterior dominant rhythm (Hz)",
             f"{bg.get('posterior_dominant_rhythm_hz', 0):.1f}"),
            ("Delta / Alpha ratio", f"{bg.get('delta_alpha_ratio', 0):.2f}"),
            ("Delta % / Theta %",
             f"{bg.get('delta_pct', 0):.0f}% / {bg.get('theta_pct', 0):.0f}%"),
            ("Alpha % / Beta %",
             f"{bg.get('alpha_pct', 0):.0f}% / {bg.get('beta_pct', 0):.0f}%"),
            ("Channels used", ", ".join(bg.get("channels_used", []))),
        ]
        norm = bg.get("age_normative_pdr")
        if norm:
            rows.append(("Age-normative PDR (Hz)", f"{norm[0]}–{norm[1]}"))
        rows.append(("Interpretation", bg.get("interpretation", "")))
        story.append(_kv_table(rows))

    # Section 4: Bursts
    br = findings.get("bursts")
    if br:
        story.append(Paragraph("Sustained Rhythmic Bursts", st["h2"]))
        rows = [
            ("Primary channel", br.get("primary_channel", "?")),
            ("Search window (h)", f"{br.get('search_window_hours', 0):.2f}"),
            ("Bursts ≥3s", str(br.get("n_bursts", 0))),
            ("Bursts ≥5s", str(br.get("n_bursts_5s_or_longer", 0))),
            ("Bursts ≥10s", str(br.get("n_bursts_10s_or_longer", 0))),
            ("Maximum duration (s)", f"{br.get('max_duration_s', 0):.1f}"),
            ("Median duration (s)", f"{br.get('median_duration_s', 0):.1f}"),
        ]
        story.append(_kv_table(rows))

    # Section 5: Morphology
    m = findings.get("morphology")
    if m:
        story.append(Paragraph("Spike Morphology", st["h2"]))
        rows = [
            ("Channel", m.get("channel", "?")),
            ("Events detected", f"{m.get('n_events', 0)} ({m.get('events_per_minute', 0):.1f}/min)"),
            ("% simple spikes (<70ms)", f"{m.get('pct_simple_spikes', 0):.0f}%"),
            ("% sharp waves (70–200ms)", f"{m.get('pct_sharp_waves', 0):.0f}%"),
            ("% complex spike-wave (≥200ms)", f"{m.get('pct_complex_spike_wave', 0):.0f}%"),
            ("Polyspike fraction", f"{m.get('polyspike_fraction', 0):.0f}%"),
            ("Duration p25/p50/p75 (ms)",
             f"{m.get('duration_p25_ms', 0)}/"
             f"{m.get('duration_p50_ms', 0)}/"
             f"{m.get('duration_p75_ms', 0)}"),
            ("Classification", m.get("classification", "")),
        ]
        story.append(_kv_table(rows))

    # ─── v0.5: SWI per sleep stage ──────────────────────────────────────
    swi = findings.get("swi")
    if swi:
        story.append(Paragraph("Spike-Wave Index (formal, per stage)", st["h2"]))
        rows = [
            ("Channel", swi.get("channel", "?")),
            ("SWI N1 (%)", str(swi.get("swi_per_stage_pct", {}).get("N1", "—"))),
            ("SWI N2 (%)", str(swi.get("swi_per_stage_pct", {}).get("N2", "—"))),
            ("SWI N3 (%)", str(swi.get("swi_per_stage_pct", {}).get("N3", "—"))),
            ("SWI REM (%)", str(swi.get("swi_per_stage_pct", {}).get("REM", "—"))),
            ("SWI Wake (%)", str(swi.get("swi_per_stage_pct", {}).get("W", "—"))),
            ("SWI NREM combined (%)", str(swi.get("swi_nrem_combined_pct", "—"))),
            ("CSWS criterion (N3 ≥ {}%)".format(
                int(swi.get("csws_threshold_pct", 85))),
                "MET" if swi.get("csws_criterion_met") else "not met"),
        ]
        story.append(_kv_table(rows))

    # ─── v0.5: Wake / NREM / REM spike rates ────────────────────────────
    state = findings.get("state_split")
    if state:
        story.append(Paragraph("Wake vs sleep spike rate", st["h2"]))
        rows = [
            ("Channel", state.get("channel", "?")),
            ("Wake spike rate (/min)", str(state.get("wake_rate_per_min", "—"))),
            ("NREM spike rate (/min)", str(state.get("nrem_rate_per_min", "—"))),
            ("REM spike rate (/min)", str(state.get("rem_rate_per_min", "—"))),
            ("Activation factor (NREM / Wake)",
             f"{state.get('activation_factor', 0):.1f}× "
             f"({state.get('activation_label', '')})"),
            ("Wake minutes analyzed", str(state.get("wake_minutes", "—"))),
            ("NREM minutes analyzed", str(state.get("nrem_minutes", "—"))),
        ]
        story.append(_kv_table(rows))

    # ─── v0.6: Sleep architecture ───────────────────────────────────────
    arch = findings.get("sleep_architecture")
    if arch:
        story.append(Paragraph("Sleep architecture", st["h2"]))
        rows = [
            ("Total sleep time (min)", str(arch.get("total_sleep_time_minutes", "—"))),
            ("Sleep onset (min from rec start)",
             str(arch.get("sleep_onset_minute", "—"))),
            ("Final awakening (min)",
             str(arch.get("final_awakening_minute", "—"))),
            ("REM latency (min)", str(arch.get("rem_latency_minutes", "—"))),
            ("WASO (Wake After Sleep Onset, min)",
             str(arch.get("waso_minutes", "—"))),
            ("Sleep fragmentation index (transitions/hr)",
             str(arch.get("fragmentation_index_per_hour", "—"))),
            ("NREM cycles (complete)", str(arch.get("n_complete_cycles", "—"))),
            ("Mean cycle duration (min)",
             str(arch.get("mean_cycle_duration_minutes", "—"))),
            ("First-cycle N3 (min)", str(arch.get("first_cycle_n3_minutes", "—"))),
        ]
        story.append(_kv_table(rows))

    # ─── v0.5: Synchrony / spread pattern ───────────────────────────────
    syn = findings.get("synchrony")
    if syn:
        story.append(Paragraph("Bilateral synchrony / spread pattern", st["h2"]))
        rows = [
            ("Events analyzed", str(syn.get("n_events_analyzed", "—"))),
            ("Dominant pattern", syn.get("dominant_pattern", "—")),
            ("Focal (%)", str(syn.get("focal_pct", "—"))),
            ("Regional (%)", str(syn.get("regional_pct", "—"))),
            ("Bilateral synchronous (%)",
             str(syn.get("bilateral_synchronous_pct", "—"))),
            ("Bilateral asynchronous (%)",
             str(syn.get("bilateral_asynchronous_pct", "—"))),
            ("Generalized (%)", str(syn.get("generalized_pct", "—"))),
            ("Median channels per event",
             str(syn.get("median_channels_per_event", "—"))),
        ]
        story.append(_kv_table(rows))

    # ─── v0.5: Sample traces ─────────────────────────────────────────────
    if sample_traces:
        from reportlab.platypus import Image as RLImage
        story.append(Paragraph("Sample EEG traces", st["h2"]))
        for caption, png_bytes in sample_traces:
            try:
                story.append(Paragraph(f"<b>{caption}</b>", st["body"]))
                img = RLImage(io.BytesIO(png_bytes), width=16 * cm, height=8 * cm)
                story.append(img)
                story.append(Spacer(1, 0.3 * cm))
            except Exception:
                # skip silently — partial PDF better than crash
                pass

    # ─── v0.17.0: Pattern Recognition section ───────────────────────────
    pr = findings.get("pattern_recognition")
    if pr and isinstance(pr, dict) and pr.get("spike_topography_pattern"):
        story.append(Paragraph("Pattern Recognition (v0.17.0)", st["h2"]))

        topo_pr = pr.get("topography", {})
        sleep_pr = pr.get("sleep_activation", {})
        morph_pr = pr.get("morphology_subtypes", {})
        ct_pr = pr.get("ct_sleep_cooccurrence", {})

        rows = [
            ("Topography pattern", str(pr.get("spike_topography_pattern", "—"))),
            ("Classification confidence", str(topo_pr.get("classification_confidence", "—"))),
            ("Asymmetry index (R-L)/(R+L)", f"{topo_pr.get('asymmetry_index', 0):.3f}"),
            ("Lateralization significant (>0.10)", str(topo_pr.get("lateralization_significant", False))),
            ("Regional kurtosis — CT",
             f"{topo_pr.get('regional_rates', {}).get('centro_temporal', 0):.2f}"),
            ("Regional kurtosis — Frontal",
             f"{topo_pr.get('regional_rates', {}).get('frontal', 0):.2f}"),
            ("Regional kurtosis — Parietal/Occipital",
             f"{topo_pr.get('regional_rates', {}).get('parietal_occipital', 0):.2f}"),
        ]
        top5 = topo_pr.get("top_5_channels", [])
        if top5:
            top5_str = ", ".join(
                f"{c.get('name','?')} ({c.get('kurtosis',0):.1f})"
                for c in top5[:5]
            )
            rows.append(("Top-5 channels (kurtosis)", top5_str))
        story.append(_kv_table(rows))

        # Morphology subtypes
        story.append(Paragraph("Spike Morphology Sub-classification", st["h2"]))
        rows_m = [
            ("Total events", str(morph_pr.get("n_total", "—"))),
            ("Short spikes <70ms", str(morph_pr.get("n_spike_short", "—"))),
            ("Sharp waves 70–200ms", str(morph_pr.get("n_sharp", "—"))),
            ("Spike-wave complex ≥200ms", str(morph_pr.get("n_sharp_wave_complex", "—"))),
            ("Polyspike count (est.)", str(morph_pr.get("n_polyspike", "—"))),
            ("Polyspike fraction (%)", f"{morph_pr.get('pct_polyspike', 0):.1f}%"),
            ("Morphology interpretation", str(morph_pr.get("interpretation", "—"))),
        ]
        story.append(_kv_table(rows_m))

        # Sleep activation
        story.append(Paragraph("Sleep Activation Classification", st["h2"]))
        rows_s = [
            ("Wake spike rate (/min)", f"{sleep_pr.get('wake_rate_per_min', 0):.2f}"),
            ("NREM spike rate (/min)", f"{sleep_pr.get('nrem_rate_per_min', 0):.2f}"),
            ("REM spike rate (/min)", f"{sleep_pr.get('rem_rate_per_min', 0):.2f}"),
            ("Activation ratio (NREM/Wake)", f"{sleep_pr.get('activation_ratio', 0):.3f}"),
            ("Classification", str(sleep_pr.get("classification", "—"))),
            ("CSWS risk score (0–1)", f"{sleep_pr.get('csws_risk_score', 0):.3f}"),
        ]
        if sleep_pr.get("notes"):
            rows_s.append(("Notes", "; ".join(sleep_pr["notes"])))
        story.append(_kv_table(rows_s))

        # CT co-occurrence
        if ct_pr:
            story.append(Paragraph("Centro-temporal Spike / Sleep Co-occurrence", st["h2"]))
            rows_ct = [
                ("Rolandic sleep-activated", str(ct_pr.get("rolandic_sleep_activated", "—"))),
                ("CT Wake rate (/min)", f"{ct_pr.get('ct_wake_rate', 0):.2f}"),
                ("CT NREM rate (/min)", f"{ct_pr.get('ct_nrem_rate', 0):.2f}"),
            ]
            story.append(_kv_table(rows_ct))

    # ─── v0.17.0: Mechanism-Targeted Findings ───────────────────────────
    ap = findings.get("aperiodic")
    ms = findings.get("microstates")
    sp_v2 = findings.get("spindles")

    if ap or ms or sp_v2:
        story.append(Paragraph("Mechanism-Targeted Findings (v0.17.0)", st["h2"]))

        if ap and isinstance(ap, dict) and ap.get("chi_by_state"):
            chi_state = ap.get("chi_by_state", {})
            ap_rows = [("Aperiodic exponent χ (state)", "Median")]
            for state_name, state_data in chi_state.items():
                if isinstance(state_data, dict):
                    med = state_data.get("median")
                    if med is not None:
                        ap_rows.append((f"  χ — {state_name}", f"{med:.3f}"))
            if len(ap_rows) > 1:
                story.append(_kv_table(ap_rows[1:]))
            # Within-tool z-scores. NOT compared against a published pediatric
            # normative cohort — no such cohort exists. Label accordingly.
            pnz = ap.get("pediatric_norm_z_scores") or {}
            if pnz:
                story.append(Paragraph(
                    "Aperiodic χ within-tool z-scores (tool-convention "
                    "reference; no published pediatric norms): " +
                    ", ".join(f"{k}={v:.2f}" for k, v in pnz.items() if v is not None),
                    st["body"],
                ))

        if ms and isinstance(ms, dict) and ms.get("coverage_pct"):
            cov = ms["coverage_pct"]
            cov_str = ", ".join(f"{k}: {v:.0f}%" for k, v in sorted(cov.items()))
            story.append(Paragraph(f"Microstates A–D: {cov_str}", st["body"]))
            dom = ms.get("dominant_microstate")
            if dom == "D":
                story.append(Paragraph(
                    "⚠ Microstate D dominant — Aufmerksamkeits/Salienz-Netzwerk-Imbalanz",
                    st["warning"],
                ))

        if sp_v2 and isinstance(sp_v2, dict) and sp_v2.get("interpretation") == "below":
            story.append(Paragraph(
                f"⚠ Spindel-Dichte stark reduziert: "
                f"{sp_v2.get('density_per_minute', 0):.2f}/min "
                f"(Norm {sp_v2.get('age_normative_range', (0.8,1.5))[0]}–"
                f"{sp_v2.get('age_normative_range', (0.8,1.5))[1]}/min) — "
                "KCNQ3-mechanistisches Korrelat",
                st["warning"],
            ))

    # ─── v0.18: Advanced quantitative metrics ───────────────────────────
    conn = findings.get("connectivity")
    sharp = findings.get("sharp_spikes")
    ocular = findings.get("ocular")
    qual = findings.get("quality") or {}
    morph_v = findings.get("morphology") or {}
    if conn or sharp or ocular:
        story.append(Paragraph("Advanced quantitative metrics (v0.18)", st["h2"]))

        # Data-quality context: bad channels + blink rate (topography caveat).
        bad_ch = qual.get("bad_channels") or []
        if bad_ch:
            story.append(Paragraph(
                "Excluded/flagged channels (auto QC): " + ", ".join(bad_ch) +
                " — averaged metrics (PDR, topography) avoid these.",
                st["body"],
            ))
        if ocular and isinstance(ocular, dict) and ocular.get("available"):
            br = ocular.get("blink_rate_per_min", 0)
            pe = ocular.get("pct_blink_epochs", 0)
            story.append(Paragraph(
                f"Eye-blink rate: {br}/min ({pe}% of epochs). Frontal "
                "topography is interpreted with blink-affected epochs excluded.",
                st["body"],
            ))

        # Spike burden: the 10-30 Hz morphology rate vs the broadband
        # sharpness-gated rate. A large gap means rhythmic contamination.
        if sharp and isinstance(sharp, dict):
            m_rate = morph_v.get("events_per_minute")
            s_rate = sharp.get("sharp_rate_per_min")
            pct_sharp = sharp.get("pct_candidates_sharp")
            if m_rate is not None and s_rate is not None:
                story.append(_kv_table([
                    ("Spike rate — morphology (10–30 Hz)", f"{m_rate:.1f}/min"),
                    ("Spike rate — broadband sharp-gated", f"{s_rate:.1f}/min"),
                    ("Candidates passing sharpness gate", f"{pct_sharp:.0f}%"),
                ]))
                if m_rate > 0 and s_rate < 0.7 * m_rate:
                    story.append(Paragraph(
                        "The broadband sharp rate is well below the 10–30 Hz "
                        "rate — part of the morphology count is rhythmic, not "
                        "spike-like. The sharp rate is the more conservative "
                        "estimate of true interictal spikes.",
                        st["body"],
                    ))

        # Connectivity (wPLI) — descriptive, intra-patient only.
        if conn and isinstance(conn, dict) and conn.get("mean_wpli_by_band"):
            wb = conn["mean_wpli_by_band"]
            story.append(Paragraph(
                "Functional connectivity (debiased wPLI, descriptive — no "
                "pediatric norms): " +
                ", ".join(f"{k} {v:.3f}" for k, v in wb.items()),
                st["body"],
            ))

    # ─── v0.19: novel quantitative metrics ──────────────────────────────
    ent_v = findings.get("entropy") or {}
    gm_v = findings.get("graph_metrics") or {}
    ictal_v = findings.get("ictal") or {}
    spkavg_v = findings.get("spike_average") or {}
    hfoc_v = findings.get("hfo_classify") or {}
    norm_v = findings.get("normative") or {}
    em = ent_v.get("metrics") or {}
    if any([em, gm_v.get("per_band"), ictal_v.get("n_candidates") is not None,
            spkavg_v.get("field_spread"), hfoc_v.get("n_real") is not None,
            norm_v.get("points")]):
        story.append(Paragraph("Novel quantitative metrics (v0.19)", st["h2"]))
        rows = []
        if em.get("sample_entropy") is not None:
            rows.append(("Sample entropy (background irregularity)",
                         f"{em['sample_entropy']:.3f}"))
        if em.get("lziv_complexity") is not None:
            rows.append(("Lempel-Ziv complexity index", f"{em['lziv_complexity']:.3f}"))
        spread = spkavg_v.get("field_spread")
        if spread and spread != "n/a":
            rows.append(("Averaged spike field spread", str(spread)))
        if hfoc_v.get("n_spike_coupled") is not None:
            rows.append(("Spike-coupled HFOs (spkHFO)", str(hfoc_v["n_spike_coupled"])))
        nc = ictal_v.get("n_candidates")
        if nc is not None:
            rows.append(("Ictal candidates (screening — needs review)", str(nc)))
        if rows:
            story.append(_kv_table(rows))
        if nc:
            story.append(Paragraph(ictal_v.get("caveat", ""), st["body"]))
        # Age-normative z-scores (placeholder norms are flagged inline).
        pts = norm_v.get("points") or []
        zline = ", ".join(f"{p['metric']} z={p['z']:+.1f}"
                          for p in pts if p.get("z") is not None)
        if zline:
            banner = ("" if norm_v.get("any_verified")
                      else "[UNVERIFIED placeholder norms — illustrative only] ")
            story.append(Paragraph(f"{banner}Age-normative z-scores: {zline}.", st["body"]))
        # Alpha-band network topology (descriptive).
        ab = (gm_v.get("per_band") or {}).get("alpha") or {}
        if ab.get("small_world_sigma") is not None:
            story.append(Paragraph(
                f"Alpha-band network (descriptive): clustering {ab.get('clustering')}, "
                f"global efficiency {ab.get('global_efficiency')}, small-world σ "
                f"{ab.get('small_world_sigma')}.", st["body"]))

    # ─── v0.17.0: KCNQ3-specific section (if variant contains KCNQ3) ────
    if variant and "KCNQ3" in str(variant).upper():
        story.append(Paragraph(f"KCNQ3-spezifische Befunde — {variant}", st["h2"]))

        # Sands 2019 comparison table
        swi_k = findings.get("swi") or {}
        state_k = findings.get("state_split") or {}
        sp_k = findings.get("spindles") or {}
        pr_k = findings.get("pattern_recognition") or {}
        topo_k = pr_k.get("topography") or {}
        sleep_k = pr_k.get("sleep_activation") or {}

        csws_k = bool(swi_k.get("csws_criterion_met", False))
        act_r_k = float(sleep_k.get("activation_ratio", 0.0))
        sp_dens_k = float(sp_k.get("density_per_minute", 0.0) or 0.0)
        sp_interp_k = sp_k.get("interpretation", "")
        topo_pat_k = pr_k.get("spike_topography_pattern", "—")
        csws_risk_k = float(pr_k.get("csws_risk_score", 0.0))

        kcnq3_rows = [
            ("Befund", "Dieser Patient", "Sands 2019 Erwartung (KCNQ3-GoF)"),
            (
                "CSWS-Kriterium",
                "ERFÜLLT" if csws_k else "NICHT erfüllt ✓",
                "60% der Kohorte betroffen",
            ),
            (
                "Schlaf-Aktivierungsratio",
                f"{act_r_k:.2f}{'  ← atypisch günstig' if act_r_k < 0.7 else ''}",
                "Moderat–stark erwartet",
            ),
            (
                "Spindel-Dichte",
                f"{sp_dens_k:.2f}/min {'(reduziert)' if sp_interp_k == 'below' else ''}",
                "Massiv reduziert (klassisch)",
            ),
            (
                "Topographisches Muster",
                topo_pat_k,
                "Multifokal mit CT-Schwerpunkt",
            ),
            (
                "CSWS-Risiko-Score",
                f"{csws_risk_k:.2f}/1.0",
                "< 0.3 günstig",
            ),
        ]

        kcnq3_tbl = Table(
            kcnq3_rows,
            colWidths=(4.5 * cm, 5 * cm, 5.5 * cm),
        )
        from reportlab.lib import colors as _colors
        kcnq3_tbl.setStyle(TableStyle([
            ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 9),
            ("FONT", (0, 1), (-1, -1), "Helvetica", 9),
            ("BACKGROUND", (0, 0), (-1, 0), _colors.HexColor("#D6E4F0")),
            ("GRID", (0, 0), (-1, -1), 0.25, _colors.lightgrey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
        ]))
        story.append(kcnq3_tbl)

        story.append(Spacer(1, 0.3 * cm))
        story.append(Paragraph(
            "<b>Literaturhinweis:</b> Sands TT et al. (2019) KCNQ3 gain-of-function epilepsy "
            "— CSWS/ESES in ~60%, prominente Schlaf-Aktivierung, stark reduzierte Spindeln. "
            "PMID 31177578.",
            st["small"],
        ))

    # ─── v0.17.0: Clinical Impression V2 ────────────────────────────────
    imp_v2 = findings.get("clinical_impression_v2")
    if imp_v2 and isinstance(imp_v2, dict) and imp_v2.get("headline"):
        story.append(Paragraph("Klinische Einschätzung (strukturiert, v0.17.0)", st["h2"]))
        story.append(Paragraph(f"<b>{imp_v2['headline']}</b>", st["body"]))

        for kf in imp_v2.get("key_findings", []):
            story.append(Paragraph(f"• {kf}", st["body"]))

        fav = imp_v2.get("favorable_factors", [])
        if fav:
            story.append(Paragraph("<b>Günstige Faktoren:</b>", st["body"]))
            for f_item in fav:
                story.append(Paragraph(f"  ✓ {f_item}", st["body"]))

        conc = imp_v2.get("concerning_factors", [])
        if conc:
            story.append(Paragraph("<b>Besorgniserregende Faktoren:</b>", st["body"]))
            for c_item in conc:
                story.append(Paragraph(f"  ⚠ {c_item}", st["warning"]))

    # ─── v0.17.0: Tracking Recommendations ─────────────────────────────
    story.append(Paragraph("Follow-up Biomarker (v0.17.0)", st["h2"]))
    tracking_rows = [
        ("Priorität", "Biomarker", "Empfohlenes Intervall"),
        ("1 (höchste)", "Spindel-Dichte (/min)", "3–6 Monate"),
        ("2", "N3 Spike-Wave Index (%)", "3–6 Monate"),
        ("3", "Aperiodic Exponent χ", "6–12 Monate"),
        ("4", "Microstate D Coverage (%)", "6–12 Monate"),
        ("5", "Topographic Spike Rate (top channel, /min)", "3–6 Monate"),
    ]
    track_tbl = Table(tracking_rows, colWidths=(3 * cm, 7 * cm, 4 * cm))
    track_tbl.setStyle(TableStyle([
        ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 9),
        ("FONT", (0, 1), (-1, -1), "Helvetica", 9),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E8EEF5")),
        ("GRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(track_tbl)

    # ─── v0.5: Methods section ───────────────────────────────────────────
    story.append(PageBreak())
    story.append(Paragraph("Methods", st["h2"]))
    methods_text = (
        f"<b>Software:</b> KCNQ3-Lens v{_VERSION} · "
        f"Analysis run: {datetime.now().strftime('%Y-%m-%d %H:%M')}<br/><br/>"
        "<b>Topography:</b> Per-channel kurtosis (Fisher=False) on 1–35 Hz "
        "bandpassed signal, per 30-second epoch.<br/><br/>"
        "<b>Sleep spindles:</b> YASA SleepStaging spindle detector "
        "(Lacourse 2019) when installed — three-criteria gate "
        "(correlation 0.65, relative power 0.20, RMS 1.5). Heuristic "
        "envelope-percentile detector as fallback.<br/><br/>"
        "<b>Background power:</b> Welch PSD on posterior channels "
        "(O1/O2/P3/P4/Pz averaged), 0.5 Hz HP + 40 Hz LP. Posterior "
        "dominant rhythm = peak in 4–13 Hz band on the wake epochs.<br/><br/>"
        "<b>Sustained bursts:</b> 5–25 Hz bandpass envelope on Pz, "
        "MAD-based threshold (4×MAD), minimum duration 3 s. Channel "
        "involvement: adaptive per-channel baseline (median peak-to-peak "
        "across 2-second tiles), channel counted as involved if "
        "burst-window peak-to-peak > 3× its baseline.<br/><br/>"
        "<b>Spike morphology:</b> Per-30s-epoch local MAD threshold "
        "(6×MAD ∪ 3×local RMS) on 10–30 Hz signal. FWHM measured on "
        "broadband 1–35 Hz signal. Classification: <70 ms = simple "
        "spike, 70–200 ms = sharp wave, ≥200 ms = complex spike-wave.<br/><br/>"
        "<b>SWI:</b> Same spike detector as morphology. Continuous SW "
        "burst = ≥1 spike/s sustained ≥3 s within an epoch. SWI per "
        "stage = total SW-burst time / total stage time × 100. CSWS "
        "criterion: N3 SWI ≥ 85% (Tassinari).<br/><br/>"
        "<b>State split:</b> Spike rates separately for wake / NREM / "
        "REM using sleep-stage labels. Activation factor = NREM-rate "
        "/ wake-rate, with wake-rate floor of 0.1 /min to avoid "
        "division by ~zero.<br/><br/>"
        "<b>Synchrony:</b> For each spike on the primary channel, "
        "channels with peak amplitude > 4×MAD within ±50 ms are "
        "counted as involved. Patterns: focal (1–2 ch), regional "
        "(3–5 ch same hemisphere), bilateral synchronous (homologous "
        "L+R pairs with balanced count), bilateral asynchronous (both "
        "sides, no balanced pairs), generalized (≥10 ch).<br/><br/>"
        "<b>Sleep stages:</b> YASA SleepStaging when installed (note: "
        "trained on adult PSG — pediatric output is heuristic). "
        "Fallback: delta/alpha ratio thresholding with 3-state output "
        "(W / N1 / N2).<br/><br/>"
        "<b>Reference ranges:</b> Spindle density McClain 2016 (age 5: "
        "~1/min at central derivations) and Kwon 2023 (developmental "
        "trajectory ages 0-18). PDR ranges Hagne 1972, Niedermeyer 2005. "
        "CSWS threshold Tassinari 1971.<br/><br/>"
        "<b>Quality grade:</b> A ≥ 80% usable + ≥15 good channels; "
        "B ≥ 65% + ≥12; C ≥ 50% + ≥8; otherwise D."
    )
    story.append(Paragraph(methods_text, st["small"]))

    # ── v0.7: Reference citations ───────────────────────────────────────
    try:
        from src.clinical.citations import all_citations
        story.append(Spacer(1, 0.3 * cm))
        story.append(Paragraph("<b>References</b>", st["small"]))
        for c in all_citations():
            pmid = f" (PMID {c.pubmed_id})" if c.pubmed_id else ""
            story.append(Paragraph(
                f"• <b>{c.short}</b>{pmid}: {c.note}", st["small"],
            ))
    except Exception:
        pass

    _disclaimer(story, st, "doctor")
    doc.build(story)
    return buf.getvalue()


# ─── Parent PDF ──────────────────────────────────────────────────────────────

def build_parent_pdf(
    findings: dict[str, Any],
    age_years: float | None = None,
    variant: str | None = None,
    interpretation: str | None = None,
    patient_label: str | None = None,
) -> bytes:
    """Generate a plain-language PDF for families to share / keep."""
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm,
        topMargin=2 * cm, bottomMargin=2 * cm,
    )
    st = _styles()
    story = []

    # Header
    title = "EEG Findings — Parent Summary"
    sub_parts = [datetime.now().strftime("%Y-%m-%d %H:%M")]
    if patient_label:
        sub_parts.append(patient_label)
    if age_years is not None:
        sub_parts.append(f"Age {age_years:.0f}")
    if variant:
        sub_parts.append(variant)
    _header(story, st, title, " · ".join(sub_parts))

    # Quick summary of the five analyses in plain language
    story.append(Paragraph("What was measured", st["h2"]))

    summary_rows = []

    sp = findings.get("spindles")
    if sp:
        norm = sp.get("age_normative_range") or (None, None)
        norm_str = f"({norm[0]}–{norm[1]} typical)" if norm[0] else ""
        flag = "⚠ low" if sp.get("interpretation") == "below" else ""
        summary_rows.append([
            "Sleep spindles",
            f"{sp.get('density_per_minute', 0):.2f} per minute {norm_str} {flag}",
        ])

    bg = findings.get("background")
    if bg:
        norm = bg.get("age_normative_pdr") or (None, None)
        norm_str = f"({norm[0]}–{norm[1]} Hz typical)" if norm[0] else ""
        flag = ""
        if bg.get("interpretation") == "severely_slow":
            flag = "⚠ slow"
        elif bg.get("interpretation") == "mildly_slow":
            flag = "mildly slow"
        summary_rows.append([
            "Background rhythm",
            f"{bg.get('posterior_dominant_rhythm_hz', 0):.1f} Hz {norm_str} {flag}",
        ])

    br = findings.get("bursts")
    if br:
        flag = "⚠ notable" if br.get("n_bursts_10s_or_longer", 0) > 0 else ""
        summary_rows.append([
            "Long rhythmic bursts",
            f"{br.get('n_bursts_10s_or_longer', 0)} bursts ≥10 seconds {flag}",
        ])

    m = findings.get("morphology")
    if m:
        flag = "⚠ complex" if m.get("classification") == "predominantly_complex" else ""
        summary_rows.append([
            "Spike type",
            f"{m.get('pct_complex_spike_wave', 0):.0f}% complex spike-wave {flag}",
        ])

    topo = findings.get("topography")
    if topo and topo.get("top_channels"):
        tops = topo["top_channels"][:3]
        tops_str = ", ".join(f"{t['name']} ({t['median_kurtosis']:.1f})" for t in tops)
        summary_rows.append([
            "Strongest activity location",
            tops_str,
        ])

    # v0.5 additions: SWI and activation factor in plain language
    swi = findings.get("swi")
    if swi:
        n3 = swi.get("swi_per_stage_pct", {}).get("N3", 0)
        flag = ""
        if swi.get("csws_criterion_met"):
            flag = "⚠ CSWS criterion met"
        elif n3 > 50:
            flag = "⚠ high"
        elif n3 > 25:
            flag = "moderate"
        summary_rows.append([
            "Spike-wave during deep sleep (SWI N3)",
            f"{n3:.0f}% of deep sleep affected {flag}",
        ])

    state = findings.get("state_split")
    if state:
        factor = state.get("activation_factor", 0)
        label = state.get("activation_label", "")
        flag = ""
        if label == "strong":
            flag = "⚠ strong"
        elif label == "moderate":
            flag = "moderate"
        summary_rows.append([
            "Sleep activation factor",
            f"{factor:.1f}× more spikes during sleep than awake {flag}",
        ])

    syn = findings.get("synchrony")
    if syn:
        summary_rows.append([
            "Spike spread pattern",
            f"Most are {syn.get('dominant_pattern', '?').replace('_', ' ')}",
        ])

    if summary_rows:
        story.append(_kv_table(summary_rows))

    # AI interpretation if available
    if interpretation:
        story.append(Spacer(1, 0.4 * cm))
        story.append(Paragraph("Plain-language interpretation", st["h2"]))
        # The interpretation is markdown; reportlab can handle basic HTML-like tags
        # Convert markdown headers and bullets to a basic readable form
        lines = interpretation.split("\n")
        for line in lines:
            line = line.strip()
            if not line:
                story.append(Spacer(1, 0.15 * cm))
                continue
            if line.startswith("###"):
                story.append(Paragraph(line.lstrip("# ").strip(), st["h2"]))
            elif line.startswith("##"):
                story.append(Paragraph(line.lstrip("# ").strip(), st["h2"]))
            elif line.startswith("- ") or line.startswith("* "):
                story.append(Paragraph("• " + line[2:], st["body"]))
            else:
                story.append(Paragraph(line, st["body"]))

    # Closing reminder
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph(
        "Bring this report to your next appointment with your child's neurologist. "
        "The numbers above are starting points for conversation, not diagnoses.",
        st["warning"],
    ))

    _disclaimer(story, st, "parent")
    doc.build(story)
    return buf.getvalue()
